"""Showcase generation with the FINAL frozen KrishiGPT-nano checkpoint.

15 representative agriculture prompts covering the domain axes of the corpus;
each decoded with the recommended setting (top-p 0.9, fixed seeds) and top-k 40
as secondary. Every sample is explicitly labeled MODEL OUTPUT — the model has
never been trained for factuality and samples must not be read as advice.

Run:  python final/showcase_samples.py
"""
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from model.generate import KrishiGenerator               # noqa: E402

CKPT = ROOT / "checkpoints" / "krishigpt_v3" / "best.pt"
TOK = ROOT / "data" / "processed" / "agri_bpe_tokenizer.json"
OUT = ROOT / "final"

PROMPTS = [
    # 1-5: original eval prompts (continuity with all prior runs)
    "The best fertilizer for wheat",
    "Soil moisture affects",
    "To control pests in the field",
    "Rice is grown in",
    "The farmer should irrigate",
    # 6-10: core agronomy / soil science
    "Crop rotation is important because",
    "Nitrogen is needed by plants for",
    "Drip irrigation saves water because",
    "A good soil for farming should have",
    "Compost improves the soil by",
    # 11-15: diseases, livestock, practice, Indian agriculture, post-harvest
    "Wheat rust is a disease that",
    "Dairy cows should be fed",
    "Before sowing the seeds the farmer should",
    "In India the kharif season begins",
    "After harvest the grain must be stored",
]

DECODES = [
    ("topp0.9", dict(top_p=0.9, seed=0)),
    ("topk40", dict(top_k=40, seed=0)),
]

MAX_TOKENS = 96


def main() -> None:
    gen = KrishiGenerator.from_checkpoint(CKPT, TOK)
    rows = []
    t0 = time.time()
    n_tokens = 0
    for dname, kw in DECODES:
        for i, p in enumerate(PROMPTS, 1):
            r = gen.sample(p, MAX_TOKENS, **kw)
            n_tokens += r.n_generated
            rows.append({
                "n": i, "variant": dname, "prompt": p,
                "kwargs": {k: v for k, v in kw.items()},
                "generated": r.text, "stop_reason": r.stop_reason,
                "n_generated": r.n_generated,
                "label": "MODEL OUTPUT — generated by KrishiGPT-nano; NOT "
                         "human-authored, NOT from the training corpus, NOT "
                         "verified agricultural advice",
            })
            print(f"[{i:>2}] {dname:<8} {p[:34]:<34} -> {r.text[:60]}...")
    tps = n_tokens / (time.time() - t0)
    payload = {
        "checkpoint": str(CKPT.relative_to(ROOT)),
        "decodes": [{"name": d, "kwargs": kw} for d, kw in DECODES],
        "max_tokens": MAX_TOKENS,
        "throughput_tps": round(tps, 1),
        "disclaimer": "All 'generated' fields are model output. KrishiGPT-nano "
                      "is a small language model with no fact-checking; treat "
                      "samples as demonstrations, not as agricultural guidance.",
        "samples": rows,
    }
    (OUT / "showcase_samples.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    lines = ["# KrishiGPT-nano (FINAL) — showcase samples",
             "",
             f"Checkpoint: `{CKPT.relative_to(ROOT)}` (frozen, step 3800, "
             f"val_loss 4.0804)",
             f"Decoding: {', '.join(d for d, _ in DECODES)} with fixed seed 0 "
             f"(default temperature); up to {MAX_TOKENS} tokens per sample.",
             "",
             "**Every sample below is MODEL OUTPUT.** It was generated by the "
             "model token-by-token; it is not human-authored, not quoted from "
             "the training corpus, and not verified agricultural advice.",
             "",
             f"End-to-end generation throughput: ~{tps:.0f} tok/s on the CPU "
             "machine during this run.", ""]
    for dname, _ in DECODES:
        lines.append(f"## {dname}")
        lines.append("")
        for row in rows:
            if row["variant"] != dname:
                continue
            lines.append(f"**{row['n']}. {row['prompt']}**")
            lines.append(f"> {row['generated']}")
            lines.append(f"> _— MODEL OUTPUT ({row['stop_reason']}, "
                         f"{row['n_generated']} tokens)_")
            lines.append("")
    (OUT / "showcase_samples.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\nsaved showcase_samples.json / .md ({n_tokens} tokens, {tps:.0f} tok/s)")


if __name__ == "__main__":
    main()
